server:
  port: 8095

# Dev
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/oauth2_jwt?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : root
    password : mydatabase

  # Naming strategy
  jpa:
    hibernate:
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    show-sql : true

  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager)

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding : utf-8
          CharSet : utf-8
          useUnicode : true
        ddl-auto: create

